version: '3'

services:

  ruby:
    image: ruby:latest
    build: 
      context: .
      dockerfile: .dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./blog:/app
    command: ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]
